---
title: "Comparação dos tempos de reação - Última Atualização: 29/06/2020"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    orientation: columns
    vertical_layout: fill
---

```{r setup, include = FALSE}
library(flexdashboard)
```

```{r}
source("PoliticasRiodeJaneiro.R") ## Leitura do script PoliticasBrasil
```

### 

Trabalho
===================================== 

### 

```{r}
readRDS("Trabalho.rds")
```

Prevenção
=====================================     

### 
    
```{r}
readRDS("Prevenção.rds")
```

Equipamento de Proteção
=====================================     

### 
    
```{r}
readRDS("Equipamento.rds")
```

Isolamento Social
=====================================     

### 
    
```{r}
readRDS("Isolamento.rds")
```

Hospital
===================================== 

### 

```{r}
readRDS("Hospital.rds")
```

Economia
=====================================     

### 
    
```{r}
readRDS("Economia.rds")
```

Flexibilização
=====================================     

### 
    
```{r}
readRDS("Flexibilização.rds")
```

Emergência de Saúde Pública
=====================================     

### 
    
```{r}
readRDS("Emergência.rds")
```


